model = construct_town("src/ABM_Input/Town_Data/abm_cityoutput_Dubois_ID_10_mile_income_ind.csv", "src/ABM_Input/Business_Data/Dubois_Idaho_10mile_biz.csv")
update_agents_attribute!(model, get_portion_random(model, 10/100), :will_mask, [true, true, true])
update_agents_attribute!(model, get_portion_random(model, 10/100), :status, :V)
seed_contagen!(model, 3)
start_run(model, 6)
